// Generated by SAM_Tas (SAM.Analytical.Tas.GenOpt, Create.TasScript) for the "tas-model" engine.
// Do not edit: every run writes it again from the optimisation definition.
// Definition: Heat pump controller
// V1 = Setpoint: tpd.controller.setpoint { controller: "HeatPumpController", plantRoom: "Plant Room" }
// Y1 = Cost (objective): tpd.annual-cost
// Y2 = CO2: tpd.annual-co2
// Y3 = Energy: tpd.annual-energy
// Chain: copy, plant simulation.

using System.Linq;
using System.Runtime.InteropServices;

var outputs = new Dictionary<string, double>();
var trace = new List<string>();
var total = System.Diagnostics.Stopwatch.StartNew();
var stage = System.Diagnostics.Stopwatch.StartNew();
var invariant = System.Globalization.CultureInfo.InvariantCulture;
string cwd = Directory.GetCurrentDirectory();

void Lap(string name)
{
    outputs["t." + name] = stage.Elapsed.TotalSeconds;
    stage.Restart();
}

double Variable(string name)
{
    TasVariable variable;
    if (!Variables.TryGetValue(name, out variable)) throw new Exception("Variable " + name + " is missing from Variables.txt.");
    return variable.VariableValue;
}

// COM arrays (the TSD's daily arrays are 1-based SAFEARRAYs): enumerate them, never index them.
float[] Floats(object values)
{
    return ((System.Collections.IEnumerable)values).Cast<object>().Select(x => System.Convert.ToSingle(x)).ToArray();
}

// Controller setpoint (exact plant room and controller names), written as a double.
void SetController(TPD.EnergyCentre energyCentre, string plantRoomName, string controllerName, double value, string output)
{
    TPD.PlantRoom plantRoom = null;
    for (int i = 1; i <= energyCentre.GetPlantRoomCount(); i++)
    {
        TPD.PlantRoom candidate = energyCentre.GetPlantRoom(i);
        if (!string.Equals(candidate.Name, plantRoomName, StringComparison.Ordinal)) continue;
        if (plantRoom != null) throw new Exception("Plant room \"" + plantRoomName + "\" found more than once.");
        plantRoom = candidate;
    }

    if (plantRoom == null) throw new Exception("Plant room \"" + plantRoomName + "\" not found.");
    TPD.PlantController controller = null;
    for (int i = 1; i <= plantRoom.GetControllerCount(); i++)
    {
        TPD.PlantController candidate = plantRoom.GetController(i);
        if (!string.Equals(candidate.Name, controllerName, StringComparison.Ordinal)) continue;
        if (controller != null) throw new Exception("Controller \"" + controllerName + "\" found more than once in \"" + plantRoomName + "\".");
        controller = candidate;
    }

    if (controller == null) throw new Exception("Controller \"" + controllerName + "\" not found in \"" + plantRoomName + "\".");
    double before = controller.Setpoint;
    controller.Setpoint = value;
    outputs[output + ".Before"] = before;
    outputs[output + ".Read"] = controller.Setpoint;
    trace.Add(string.Format(invariant, "{0} controller \"{1}\" ({2}) setpoint {3} -> {4}", output, controllerName, controller.SensorType, before, controller.Setpoint));
}

// Annual TPD result: the first value of every item of the type, summed.
double ResultSum(TPD.WrResultSet resultSet, TPD.tpdResultVectorType type)
{
    double sum = 0;
    int size = resultSet.GetVectorSize(type);
    for (int i = 1; i <= size; i++)
    {
        TPD.WrResultItem item = (TPD.WrResultItem)resultSet.GetResultItem(type, i);
        Array values = (Array)item.GetValues();
        sum += (double)values.GetValue(0);
    }

    return sum;
}

// ---- 1. Copy the workspace files into the evaluation folder (the workspace snapshot is never written).
string tbdPath = Path.Combine(cwd, "model.tbd");
string tsdPath = Path.Combine(cwd, "model.tsd");
string tpdPath = Path.Combine(cwd, "model.tpd");
File.Copy(TasFiles.getFiles(TasGenComm.TasFiles.TasExtension.TBD)["Systems Training.tbd"].FullPath, tbdPath, true);
File.Copy(TasFiles.getFiles(TasGenComm.TasFiles.TasExtension.TSD)["Systems Training.tsd"].FullPath, tsdPath, true);
File.Copy(TasFiles.getFiles(TasGenComm.TasFiles.TasExtension.TPD)["Systems Training.tpd"].FullPath, tpdPath, true);
Lap("Copy");

// ---- 4. Plant: point the TPD at this TSD, set the controllers, simulate, read the annual results.
// FixTSDPath fails when the TBD named inside the TSD (SimulationData.buildingPath, absolute) does not exist
// (PR7a F1): point it at the evaluation's TBD first.
TSD.TSDDocument tsdFix = new TSD.TSDDocument();
tsdFix.open(tsdPath);
tsdFix.SimulationData.buildingPath = tbdPath;
tsdFix.save();
tsdFix.close();
Marshal.FinalReleaseComObject(tsdFix);
Lap("TsdBuildingPath");
TPD.TPDDoc tpdDocument = new TPD.TPDDoc();
tpdDocument.Open(tpdPath);
TPD.EnergyCentre energyCentre = tpdDocument.EnergyCentre;
if (energyCentre.GetTSDDataCount() != 1) throw new Exception("The TPD uses " + energyCentre.GetTSDDataCount() + " TSD files; the tas-model engine supports one.");
energyCentre.GetTSDData(1).FixTSDPath(tsdPath);
SetController(energyCentre, "Plant Room", "HeatPumpController", Variable("V1"), "V1");
Lap("TpdEdit");
// The Systems Demo's simulation call, for every plant room.
for (int i = 1; i <= energyCentre.GetPlantRoomCount(); i++)
{
    energyCentre.GetPlantRoom(i).SimulateEx(1, 8760, 0, energyCentre.ExternalPollutant.Value, 10.0, (int)TPD.tpdSimulationData.tpdSimulationDataLoad + (int)TPD.tpdSimulationData.tpdSimulationDataPipe, 0, 0);
}

Lap("PlantSimulation");
// Read every result before the TPD is released (PR7a F2: TPD.exe may crash at shutdown, after this).
TPD.WrResultSet resultSet = (TPD.WrResultSet)energyCentre.GetResultSet(TPD.tpdResultsPeriod.tpdResultsPeriodAnnual, 0, 0, 0, null);
double plantEnergy = ResultSum(resultSet, TPD.tpdResultVectorType.tpdConsumption);
double plantCost = ResultSum(resultSet, TPD.tpdResultVectorType.tpdCost);
double plantCO2 = ResultSum(resultSet, TPD.tpdResultVectorType.tpdCo2);
resultSet.Dispose();
Lap("PlantRead");
Marshal.FinalReleaseComObject(tpdDocument);
Lap("TpdClose");

// ---- 5. Outputs: the objective as Result and Y1, then the recorded outputs, then the read-back values.
outputs["t.Total"] = total.Elapsed.TotalSeconds;
File.WriteAllLines(Path.Combine(cwd, "tas-model-trace.txt"), trace);
ScriptOutput.SetValue("Result", plantCost);
ScriptOutput.SetValue("Y1", plantCost);
ScriptOutput.SetValue("Y2", plantCO2);
ScriptOutput.SetValue("Y3", plantEnergy);
foreach (var pair in outputs) ScriptOutput.SetValue(pair.Key, pair.Value);
