// Generated by SAM_Tas (SAM.Analytical.Tas.GenOpt, Create.TasScript) for the "tas-model" engine.
// Do not edit: every run writes it again from the optimisation definition.
// Definition: Setpoint and controller
// V1 = Heating: tbd.internal-condition.heating-setpoint { internalCondition: "Office Weekday" }
// V2 = Controller: tpd.controller.setpoint { controller: "HeatPumpController", plantRoom: "Plant Room" }
// Y1 = Energy (objective): tpd.annual-energy
// Y2 = Heating demand: tsd.annual-heating-demand
// Y3 = Overheating: tsd.overheating-hours
// Chain: copy, building simulation, building results, plant simulation.

using System.Linq;
using System.Runtime.InteropServices;

var outputs = new Dictionary<string, double>();
var trace = new List<string>();
var total = System.Diagnostics.Stopwatch.StartNew();
var stage = System.Diagnostics.Stopwatch.StartNew();
var invariant = System.Globalization.CultureInfo.InvariantCulture;
string cwd = Directory.GetCurrentDirectory();

void Lap(string name)
{
    outputs["t." + name] = stage.Elapsed.TotalSeconds;
    stage.Restart();
}

double Variable(string name)
{
    TasVariable variable;
    if (!Variables.TryGetValue(name, out variable)) throw new Exception("Variable " + name + " is missing from Variables.txt.");
    return variable.VariableValue;
}

// COM arrays (the TSD's daily arrays are 1-based SAFEARRAYs): enumerate them, never index them.
float[] Floats(object values)
{
    return ((System.Collections.IEnumerable)values).Cast<object>().Select(x => System.Convert.ToSingle(x)).ToArray();
}

// The TSD is still being written when simulate returns.
void WaitToUnlock(string path)
{
    var watch = System.Diagnostics.Stopwatch.StartNew();
    while (watch.Elapsed.TotalSeconds < 120)
    {
        try
        {
            using (new FileStream(path, FileMode.Open, FileAccess.ReadWrite, FileShare.None)) { }
            return;
        }
        catch (IOException)
        {
            System.Threading.Thread.Sleep(100);
        }
    }

    throw new Exception("File still locked after 120 s: " + Path.GetFileName(path));
}

// Zone setpoint of one internal condition (exact name): heating = thermostat lower limit (ticLL), cooling = upper
// limit (ticUL). A value profile's value changes (setback and schedule kept); in a 24-hour profile the hours at the
// setpoint (heating: highest, cooling: lowest) change and the other hours are kept. Factor 1 only.
void SetSetpoint(TBD.Building building, string internalConditionName, bool heating, double value, string output)
{
    var matches = new List<TBD.InternalCondition>();
    for (int i = 0; ; i++)
    {
        TBD.InternalCondition candidate = building.GetIC(i);
        if (candidate == null) break;
        if (string.Equals(candidate.name, internalConditionName, StringComparison.Ordinal)) matches.Add(candidate);
    }

    if (matches.Count != 1) throw new Exception("Internal condition \"" + internalConditionName + "\" found " + matches.Count + " times.");
    string what = heating ? "Heating" : "Cooling";
    TBD.profile profile = matches[0].GetThermostat().GetProfile((int)(heating ? TBD.Profiles.ticLL : TBD.Profiles.ticUL));
    if (profile.factor != 1) throw new Exception(what + " setpoint of \"" + internalConditionName + "\" has factor " + profile.factor + "; only factor 1 is supported.");
    float before;
    if (profile.type == TBD.ProfileTypes.ticValueProfile)
    {
        before = profile.value;
        profile.value = (float)value;
        outputs[output + ".Read"] = profile.value;
    }
    else if (profile.type == TBD.ProfileTypes.ticHourlyProfile)
    {
        float[] hours = new float[24];
        for (int h = 1; h <= 24; h++) hours[h - 1] = profile.hourlyValues[h];
        before = heating ? hours.Max() : hours.Min();
        int changed = 0;
        for (int h = 1; h <= 24; h++)
        {
            if (hours[h - 1] == before) { profile.hourlyValues[h] = (float)value; changed++; }
        }

        outputs[output + ".Read"] = heating ? Enumerable.Range(1, 24).Max(h => profile.hourlyValues[h]) : Enumerable.Range(1, 24).Min(h => profile.hourlyValues[h]);
        outputs[output + ".Hours"] = changed;
    }
    else
    {
        throw new Exception(what + " setpoint of \"" + internalConditionName + "\" is a " + profile.type + "; only value and 24-hour profiles are supported.");
    }

    outputs[output + ".Before"] = before;
    trace.Add(string.Format(invariant, "{0} {1} setpoint of \"{2}\" ({3}) {4} -> {5}", output, what, internalConditionName, profile.type, before, value));
}

// Controller setpoint (exact plant room and controller names), written as a double.
void SetController(TPD.EnergyCentre energyCentre, string plantRoomName, string controllerName, double value, string output)
{
    TPD.PlantRoom plantRoom = null;
    for (int i = 1; i <= energyCentre.GetPlantRoomCount(); i++)
    {
        TPD.PlantRoom candidate = energyCentre.GetPlantRoom(i);
        if (!string.Equals(candidate.Name, plantRoomName, StringComparison.Ordinal)) continue;
        if (plantRoom != null) throw new Exception("Plant room \"" + plantRoomName + "\" found more than once.");
        plantRoom = candidate;
    }

    if (plantRoom == null) throw new Exception("Plant room \"" + plantRoomName + "\" not found.");
    TPD.PlantController controller = null;
    for (int i = 1; i <= plantRoom.GetControllerCount(); i++)
    {
        TPD.PlantController candidate = plantRoom.GetController(i);
        if (!string.Equals(candidate.Name, controllerName, StringComparison.Ordinal)) continue;
        if (controller != null) throw new Exception("Controller \"" + controllerName + "\" found more than once in \"" + plantRoomName + "\".");
        controller = candidate;
    }

    if (controller == null) throw new Exception("Controller \"" + controllerName + "\" not found in \"" + plantRoomName + "\".");
    double before = controller.Setpoint;
    controller.Setpoint = value;
    outputs[output + ".Before"] = before;
    outputs[output + ".Read"] = controller.Setpoint;
    trace.Add(string.Format(invariant, "{0} controller \"{1}\" ({2}) setpoint {3} -> {4}", output, controllerName, controller.SensorType, before, controller.Setpoint));
}

// Annual TPD result: the first value of every item of the type, summed.
double ResultSum(TPD.WrResultSet resultSet, TPD.tpdResultVectorType type)
{
    double sum = 0;
    int size = resultSet.GetVectorSize(type);
    for (int i = 1; i <= size; i++)
    {
        TPD.WrResultItem item = (TPD.WrResultItem)resultSet.GetResultItem(type, i);
        Array values = (Array)item.GetValues();
        sum += (double)values.GetValue(0);
    }

    return sum;
}

// ---- 1. Copy the workspace files into the evaluation folder (the workspace snapshot is never written).
string tbdPath = Path.Combine(cwd, "model.tbd");
string tsdPath = Path.Combine(cwd, "model.tsd");
string tpdPath = Path.Combine(cwd, "model.tpd");
File.Copy(TasFiles.getFiles(TasGenComm.TasFiles.TasExtension.TBD)["Systems Training.tbd"].FullPath, tbdPath, true);
File.Copy(TasFiles.getFiles(TasGenComm.TasFiles.TasExtension.TPD)["Systems Training.tpd"].FullPath, tpdPath, true);
Lap("Copy");

// ---- 2. Building: edit the TBD, then simulate TBD -> TSD (as SAM_Tas Modify.Simulate).
TBD.TBDDocument tbdDocument = new TBD.TBDDocument();
tbdDocument.open(tbdPath);
TBD.Building tbdBuilding = tbdDocument.Building;
SetSetpoint(tbdBuilding, "Office Weekday", true, Variable("V1"), "V1");
Lap("TbdEdit");
tbdDocument.save();
tbdDocument.simulate(1, 365, 0, 1, 0, 0, tsdPath, 1, 0);
Lap("BuildingSimulation");
WaitToUnlock(tsdPath);
tbdDocument.save();
tbdDocument.close();
Marshal.FinalReleaseComObject(tbdDocument);
Lap("TbdClose");

// ---- 3. Building results from the TSD (only the arrays the outputs need).
TSD.TSDDocument tsdDocument = new TSD.TSDDocument();
tsdDocument.openReadOnly(tsdPath);
TSD.BuildingData buildingData = tsdDocument.SimulationData.GetBuildingData();
// W each hour, summed over the year = Wh; in kWh.
double heatingDemand = Floats(buildingData.GetAnnualBuildingResult((int)TSD.tsdBuildingArray.heatingProfile)).Sum(x => (double)x) / 1000;
// Overheating: occupied hours (occupant sensible gain > 0) with resultant temperature above the threshold, per
// zone; the worst occupied zone counts (the same rule as SAM_Tas Query.Overheating).
double[] thresholds = new double[] { 28 };
int[] overheating = new int[thresholds.Length];
for (int z = 1; z <= buildingData.zoneCount; z++)
{
    TSD.ZoneData zoneData = buildingData.GetZoneData(z);
    int occupied = 0;
    int[] over = new int[thresholds.Length];
    for (int day = 1; day <= 365; day++)
    {
        float[] gain = Floats(zoneData.GetDailyZoneResult(day, (short)TSD.tsdZoneArray.occupantSensibleGain));
        float[] resultant = Floats(zoneData.GetDailyZoneResult(day, (short)TSD.tsdZoneArray.resultantTemp));
        for (int h = 0; h < 24; h++)
        {
            if (gain[h] <= 0) continue;
            occupied++;
            for (int t = 0; t < thresholds.Length; t++)
            {
                if (resultant[h] > thresholds[t]) over[t]++;
            }
        }
    }

    if (occupied == 0) continue;
    for (int t = 0; t < thresholds.Length; t++)
    {
        if (over[t] > overheating[t])
        {
            overheating[t] = over[t];
            trace.Add(string.Format(invariant, "over {0} degC: zone \"{1}\" {2} h of {3} occupied", thresholds[t], zoneData.name, over[t], occupied));
        }
    }
}

tsdDocument.close();
Marshal.FinalReleaseComObject(tsdDocument);
Lap("TsdRead");

// ---- 4. Plant: point the TPD at this TSD, set the controllers, simulate, read the annual results.
TPD.TPDDoc tpdDocument = new TPD.TPDDoc();
tpdDocument.Open(tpdPath);
TPD.EnergyCentre energyCentre = tpdDocument.EnergyCentre;
if (energyCentre.GetTSDDataCount() != 1) throw new Exception("The TPD uses " + energyCentre.GetTSDDataCount() + " TSD files; the tas-model engine supports one.");
energyCentre.GetTSDData(1).FixTSDPath(tsdPath);
SetController(energyCentre, "Plant Room", "HeatPumpController", Variable("V2"), "V2");
Lap("TpdEdit");
// The Systems Demo's simulation call, for every plant room.
for (int i = 1; i <= energyCentre.GetPlantRoomCount(); i++)
{
    energyCentre.GetPlantRoom(i).SimulateEx(1, 8760, 0, energyCentre.ExternalPollutant.Value, 10.0, (int)TPD.tpdSimulationData.tpdSimulationDataLoad + (int)TPD.tpdSimulationData.tpdSimulationDataPipe, 0, 0);
}

Lap("PlantSimulation");
// Read every result before the TPD is released (PR7a F2: TPD.exe may crash at shutdown, after this).
TPD.WrResultSet resultSet = (TPD.WrResultSet)energyCentre.GetResultSet(TPD.tpdResultsPeriod.tpdResultsPeriodAnnual, 0, 0, 0, null);
double plantEnergy = ResultSum(resultSet, TPD.tpdResultVectorType.tpdConsumption);
resultSet.Dispose();
Lap("PlantRead");
Marshal.FinalReleaseComObject(tpdDocument);
Lap("TpdClose");

// ---- 5. Outputs: the objective as Result and Y1, then the recorded outputs, then the read-back values.
outputs["t.Total"] = total.Elapsed.TotalSeconds;
File.WriteAllLines(Path.Combine(cwd, "tas-model-trace.txt"), trace);
ScriptOutput.SetValue("Result", plantEnergy);
ScriptOutput.SetValue("Y1", plantEnergy);
ScriptOutput.SetValue("Y2", heatingDemand);
ScriptOutput.SetValue("Y3", overheating[0]);
foreach (var pair in outputs) ScriptOutput.SetValue(pair.Key, pair.Value);
