// Generated by SAM_Tas (SAM.Analytical.Tas.GenOpt, Create.TasScript) for the "tas-model" engine.
// Do not edit: every run writes it again from the optimisation definition.
// Definition: Glazing choice
// V1 = Glazing: tbd.glazing-construction.choice { glazingConstruction: "Windows: SIM_EXT_GLZ -pane" } options [Windows: SIM_EXT_GLZ -pane | Double B | Triple low-e]
// Y1 = Overheating (objective): tsd.overheating-hours (threshold 28)
// Y2 = Cooling demand: tsd.annual-cooling-demand
// Chain: copy, building simulation, building results.

using System.Linq;
using System.Runtime.InteropServices;

var outputs = new Dictionary<string, double>();
var trace = new List<string>();
var total = System.Diagnostics.Stopwatch.StartNew();
var stage = System.Diagnostics.Stopwatch.StartNew();
var invariant = System.Globalization.CultureInfo.InvariantCulture;
string cwd = Directory.GetCurrentDirectory();

void Lap(string name)
{
    outputs["t." + name] = stage.Elapsed.TotalSeconds;
    stage.Restart();
}

double Variable(string name)
{
    TasVariable variable;
    if (!Variables.TryGetValue(name, out variable)) throw new Exception("Variable " + name + " is missing from Variables.txt.");
    return variable.VariableValue;
}

// COM arrays (the TSD's daily arrays are 1-based SAFEARRAYs): enumerate them, never index them.
float[] Floats(object values)
{
    return ((System.Collections.IEnumerable)values).Cast<object>().Select(x => System.Convert.ToSingle(x)).ToArray();
}

// The TSD is still being written when simulate returns.
void WaitToUnlock(string path)
{
    var watch = System.Diagnostics.Stopwatch.StartNew();
    while (watch.Elapsed.TotalSeconds < 120)
    {
        try
        {
            using (new FileStream(path, FileMode.Open, FileAccess.ReadWrite, FileShare.None)) { }
            return;
        }
        catch (IOException)
        {
            System.Threading.Thread.Sleep(100);
        }
    }

    throw new Exception("File still locked after 120 s: " + Path.GetFileName(path));
}

// Glazing choice: every building element using the target glazing construction (exact name) is given the option's
// pane construction (written into the TBD under a unique name before the run); the frames are kept.
void SetGlazing(TBD.Building building, string glazingConstruction, double value, string[] panes, string[] labels, string output)
{
    int option = (int)Math.Round(value);
    if (option < 1 || option > panes.Length || Math.Abs(value - option) > 1e-9)
        throw new Exception(output + " = " + value.ToString(invariant) + " is not an option number 1.." + panes.Length + ".");

    var elements = new List<TBD.buildingElement>();
    for (int i = 0; ; i++)
    {
        TBD.buildingElement element = building.GetBuildingElement(i);
        if (element == null) break;
        TBD.Construction construction = element.GetConstruction();
        if (construction != null && string.Equals(construction.name, glazingConstruction, StringComparison.Ordinal)) elements.Add(element);
    }

    if (elements.Count == 0) throw new Exception("No building element uses the glazing construction \"" + glazingConstruction + "\".");
    string paneName = panes[option - 1];
    TBD.Construction pane = building.GetConstructionByName(paneName);
    if (pane == null || pane.type != TBD.ConstructionTypes.tcdTransparentConstruction)
        throw new Exception("Glazing option " + option + " pane construction \"" + paneName + "\" not found in the TBD.");
    if (!string.Equals(paneName, glazingConstruction, StringComparison.Ordinal))
    {
        foreach (TBD.buildingElement element in elements) element.AssignConstruction(pane);
    }

    if (elements.Any(x => !string.Equals(x.GetConstruction().name, paneName, StringComparison.Ordinal)))
        throw new Exception("Glazing option " + option + " was not assigned.");
    float[] values = Floats(elements[0].GetConstruction().GetGlazingValues());
    float[] u = Floats(elements[0].GetConstruction().GetUValue());
    outputs[output + ".Option"] = option;
    outputs[output + ".g"] = values[5];
    outputs[output + ".U"] = u[6];
    outputs[output + ".Light"] = values[0];
    outputs[output + ".Elements"] = elements.Count;
    trace.Add(string.Format(invariant, "{0} glazing option {1} \"{2}\": pane \"{3}\" on {4} elements; g {5}, U {6}, light {7}", output, option, labels[option - 1], paneName, elements.Count, values[5], u[6], values[0]));
}

// ---- 1. Copy the workspace files into the evaluation folder (the workspace snapshot is never written).
string tbdPath = Path.Combine(cwd, "model.tbd");
string tsdPath = Path.Combine(cwd, "model.tsd");
File.Copy(TasFiles.getFiles(TasGenComm.TasFiles.TasExtension.TBD)["000000_SAM_AnalyticalModel.tbd"].FullPath, tbdPath, true);
Lap("Copy");

// ---- 2. Building: edit the TBD, then simulate TBD -> TSD (as SAM_Tas Modify.Simulate).
TBD.TBDDocument tbdDocument = new TBD.TBDDocument();
tbdDocument.open(tbdPath);
TBD.Building tbdBuilding = tbdDocument.Building;
SetGlazing(tbdBuilding, "Windows: SIM_EXT_GLZ -pane", Variable("V1"),
    new[] { "Windows: SIM_EXT_GLZ -pane", "Windows: Double B ff1c5e -pane", "Windows: Triple low-e a5191c -pane" },
    new[] { "Windows: SIM_EXT_GLZ -pane", "Double B", "Triple low-e" },
    "V1");
Lap("TbdEdit");
tbdDocument.save();
tbdDocument.simulate(1, 365, 0, 1, 0, 0, tsdPath, 1, 0);
Lap("BuildingSimulation");
WaitToUnlock(tsdPath);
tbdDocument.save();
tbdDocument.close();
Marshal.FinalReleaseComObject(tbdDocument);
Lap("TbdClose");

// ---- 3. Building results from the TSD (only the arrays the outputs need).
TSD.TSDDocument tsdDocument = new TSD.TSDDocument();
tsdDocument.openReadOnly(tsdPath);
TSD.BuildingData buildingData = tsdDocument.SimulationData.GetBuildingData();
double coolingDemand = Floats(buildingData.GetAnnualBuildingResult((int)TSD.tsdBuildingArray.coolingProfile)).Sum(x => (double)x) / 1000;
// Overheating: occupied hours (occupant sensible gain > 0) with resultant temperature above the threshold, per
// zone; the worst occupied zone counts (the same rule as SAM_Tas Query.Overheating).
double[] thresholds = new double[] { 28 };
int[] overheating = new int[thresholds.Length];
for (int z = 1; z <= buildingData.zoneCount; z++)
{
    TSD.ZoneData zoneData = buildingData.GetZoneData(z);
    int occupied = 0;
    int[] over = new int[thresholds.Length];
    for (int day = 1; day <= 365; day++)
    {
        float[] gain = Floats(zoneData.GetDailyZoneResult(day, (short)TSD.tsdZoneArray.occupantSensibleGain));
        float[] resultant = Floats(zoneData.GetDailyZoneResult(day, (short)TSD.tsdZoneArray.resultantTemp));
        for (int h = 0; h < 24; h++)
        {
            if (gain[h] <= 0) continue;
            occupied++;
            for (int t = 0; t < thresholds.Length; t++)
            {
                if (resultant[h] > thresholds[t]) over[t]++;
            }
        }
    }

    if (occupied == 0) continue;
    for (int t = 0; t < thresholds.Length; t++)
    {
        if (over[t] > overheating[t])
        {
            overheating[t] = over[t];
            trace.Add(string.Format(invariant, "over {0} degC: zone \"{1}\" {2} h of {3} occupied", thresholds[t], zoneData.name, over[t], occupied));
        }
    }
}

tsdDocument.close();
Marshal.FinalReleaseComObject(tsdDocument);
Lap("TsdRead");

// ---- 5. Outputs: the objective as Result and Y1, then the recorded outputs, then the read-back values.
outputs["t.Total"] = total.Elapsed.TotalSeconds;
File.WriteAllLines(Path.Combine(cwd, "tas-model-trace.txt"), trace);
ScriptOutput.SetValue("Result", overheating[0]);
ScriptOutput.SetValue("Y1", overheating[0]);
ScriptOutput.SetValue("Y2", coolingDemand);
foreach (var pair in outputs) ScriptOutput.SetValue(pair.Key, pair.Value);
