// Generated by SAM_Tas (SAM.Analytical.Tas.GenOpt, Create.TasScript) for the "tas-model" engine.
// Do not edit: every run writes it again from the optimisation definition.
// Definition: Office setpoints
// V1 = Heating, office: tbd.internal-condition.heating-setpoint { internalCondition: "Office Weekday" }
// V2 = Cooling: tbd.internal-condition.cooling-setpoint { internalCondition: "Office Weekday" }
// Y1 = Heating demand (objective): tsd.annual-heating-demand
// Y2 = Cooling demand: tsd.annual-cooling-demand
// Y3 = Overheating 25: tsd.overheating-hours (threshold 25)
// Y4 = Overheating: tsd.overheating-hours
// Chain: copy, building simulation, building results.

using System.Linq;
using System.Runtime.InteropServices;

var outputs = new Dictionary<string, double>();
var trace = new List<string>();
var total = System.Diagnostics.Stopwatch.StartNew();
var stage = System.Diagnostics.Stopwatch.StartNew();
var invariant = System.Globalization.CultureInfo.InvariantCulture;
string cwd = Directory.GetCurrentDirectory();

void Lap(string name)
{
    outputs["t." + name] = stage.Elapsed.TotalSeconds;
    stage.Restart();
}

double Variable(string name)
{
    TasVariable variable;
    if (!Variables.TryGetValue(name, out variable)) throw new Exception("Variable " + name + " is missing from Variables.txt.");
    return variable.VariableValue;
}

// COM arrays (the TSD's daily arrays are 1-based SAFEARRAYs): enumerate them, never index them.
float[] Floats(object values)
{
    return ((System.Collections.IEnumerable)values).Cast<object>().Select(x => System.Convert.ToSingle(x)).ToArray();
}

// The TSD is still being written when simulate returns.
void WaitToUnlock(string path)
{
    var watch = System.Diagnostics.Stopwatch.StartNew();
    while (watch.Elapsed.TotalSeconds < 120)
    {
        try
        {
            using (new FileStream(path, FileMode.Open, FileAccess.ReadWrite, FileShare.None)) { }
            return;
        }
        catch (IOException)
        {
            System.Threading.Thread.Sleep(100);
        }
    }

    throw new Exception("File still locked after 120 s: " + Path.GetFileName(path));
}

// Zone setpoint of one internal condition (exact name): heating = thermostat lower limit (ticLL), cooling = upper
// limit (ticUL). A value profile's value changes (setback and schedule kept); in a 24-hour profile the hours at the
// setpoint (heating: highest, cooling: lowest) change and the other hours are kept. Factor 1 only.
void SetSetpoint(TBD.Building building, string internalConditionName, bool heating, double value, string output)
{
    var matches = new List<TBD.InternalCondition>();
    for (int i = 0; ; i++)
    {
        TBD.InternalCondition candidate = building.GetIC(i);
        if (candidate == null) break;
        if (string.Equals(candidate.name, internalConditionName, StringComparison.Ordinal)) matches.Add(candidate);
    }

    if (matches.Count != 1) throw new Exception("Internal condition \"" + internalConditionName + "\" found " + matches.Count + " times.");
    string what = heating ? "Heating" : "Cooling";
    TBD.profile profile = matches[0].GetThermostat().GetProfile((int)(heating ? TBD.Profiles.ticLL : TBD.Profiles.ticUL));
    if (profile.factor != 1) throw new Exception(what + " setpoint of \"" + internalConditionName + "\" has factor " + profile.factor + "; only factor 1 is supported.");
    float before;
    if (profile.type == TBD.ProfileTypes.ticValueProfile)
    {
        before = profile.value;
        profile.value = (float)value;
        outputs[output + ".Read"] = profile.value;
    }
    else if (profile.type == TBD.ProfileTypes.ticHourlyProfile)
    {
        float[] hours = new float[24];
        for (int h = 1; h <= 24; h++) hours[h - 1] = profile.hourlyValues[h];
        before = heating ? hours.Max() : hours.Min();
        int changed = 0;
        for (int h = 1; h <= 24; h++)
        {
            if (hours[h - 1] == before) { profile.hourlyValues[h] = (float)value; changed++; }
        }

        outputs[output + ".Read"] = heating ? Enumerable.Range(1, 24).Max(h => profile.hourlyValues[h]) : Enumerable.Range(1, 24).Min(h => profile.hourlyValues[h]);
        outputs[output + ".Hours"] = changed;
    }
    else
    {
        throw new Exception(what + " setpoint of \"" + internalConditionName + "\" is a " + profile.type + "; only value and 24-hour profiles are supported.");
    }

    outputs[output + ".Before"] = before;
    trace.Add(string.Format(invariant, "{0} {1} setpoint of \"{2}\" ({3}) {4} -> {5}", output, what, internalConditionName, profile.type, before, value));
}

// ---- 1. Copy the workspace files into the evaluation folder (the workspace snapshot is never written).
string tbdPath = Path.Combine(cwd, "model.tbd");
string tsdPath = Path.Combine(cwd, "model.tsd");
File.Copy(TasFiles.getFiles(TasGenComm.TasFiles.TasExtension.TBD)["Systems Training.tbd"].FullPath, tbdPath, true);
Lap("Copy");

// ---- 2. Building: edit the TBD, then simulate TBD -> TSD (as SAM_Tas Modify.Simulate).
TBD.TBDDocument tbdDocument = new TBD.TBDDocument();
tbdDocument.open(tbdPath);
TBD.Building tbdBuilding = tbdDocument.Building;
SetSetpoint(tbdBuilding, "Office Weekday", true, Variable("V1"), "V1");
SetSetpoint(tbdBuilding, "Office Weekday", false, Variable("V2"), "V2");
Lap("TbdEdit");
tbdDocument.save();
tbdDocument.simulate(1, 365, 0, 1, 0, 0, tsdPath, 1, 0);
Lap("BuildingSimulation");
WaitToUnlock(tsdPath);
tbdDocument.save();
tbdDocument.close();
Marshal.FinalReleaseComObject(tbdDocument);
Lap("TbdClose");

// ---- 3. Building results from the TSD (only the arrays the outputs need).
TSD.TSDDocument tsdDocument = new TSD.TSDDocument();
tsdDocument.openReadOnly(tsdPath);
TSD.BuildingData buildingData = tsdDocument.SimulationData.GetBuildingData();
// W each hour, summed over the year = Wh; in kWh.
double heatingDemand = Floats(buildingData.GetAnnualBuildingResult((int)TSD.tsdBuildingArray.heatingProfile)).Sum(x => (double)x) / 1000;
double coolingDemand = Floats(buildingData.GetAnnualBuildingResult((int)TSD.tsdBuildingArray.coolingProfile)).Sum(x => (double)x) / 1000;
// Overheating: occupied hours (occupant sensible gain > 0) with resultant temperature above the threshold, per
// zone; the worst occupied zone counts (the same rule as SAM_Tas Query.Overheating).
double[] thresholds = new double[] { 25, 28 };
int[] overheating = new int[thresholds.Length];
for (int z = 1; z <= buildingData.zoneCount; z++)
{
    TSD.ZoneData zoneData = buildingData.GetZoneData(z);
    int occupied = 0;
    int[] over = new int[thresholds.Length];
    for (int day = 1; day <= 365; day++)
    {
        float[] gain = Floats(zoneData.GetDailyZoneResult(day, (short)TSD.tsdZoneArray.occupantSensibleGain));
        float[] resultant = Floats(zoneData.GetDailyZoneResult(day, (short)TSD.tsdZoneArray.resultantTemp));
        for (int h = 0; h < 24; h++)
        {
            if (gain[h] <= 0) continue;
            occupied++;
            for (int t = 0; t < thresholds.Length; t++)
            {
                if (resultant[h] > thresholds[t]) over[t]++;
            }
        }
    }

    if (occupied == 0) continue;
    for (int t = 0; t < thresholds.Length; t++)
    {
        if (over[t] > overheating[t])
        {
            overheating[t] = over[t];
            trace.Add(string.Format(invariant, "over {0} degC: zone \"{1}\" {2} h of {3} occupied", thresholds[t], zoneData.name, over[t], occupied));
        }
    }
}

tsdDocument.close();
Marshal.FinalReleaseComObject(tsdDocument);
Lap("TsdRead");

// ---- 5. Outputs: the objective as Result and Y1, then the recorded outputs, then the read-back values.
outputs["t.Total"] = total.Elapsed.TotalSeconds;
File.WriteAllLines(Path.Combine(cwd, "tas-model-trace.txt"), trace);
ScriptOutput.SetValue("Result", heatingDemand);
ScriptOutput.SetValue("Y1", heatingDemand);
ScriptOutput.SetValue("Y2", coolingDemand);
ScriptOutput.SetValue("Y3", overheating[0]);
ScriptOutput.SetValue("Y4", overheating[1]);
foreach (var pair in outputs) ScriptOutput.SetValue(pair.Key, pair.Value);
